# Generated by Django 3.0.1 on 2019-12-25 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
