# Generated by Django 3.0.1 on 2019-12-25 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('awarded_to', models.CharField(max_length=128)),
                ('awarded_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=256)),
                ('user_id', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='email',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
