# Generated by Django 3.0.1 on 2019-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191227_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user_id',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
