# Generated by Django 3.0.1 on 2019-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organisation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='organisation_associated',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
