# Generated by Django 3.0.1 on 2019-12-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191226_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chain',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
