# Generated by Django 3.1.5 on 2021-01-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_certificate_remarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Params',
            new_name='Param',
        ),
    ]
